In [1]:
from numpy import linalg
import numpy as np
from math import floor
from matplotlib import pyplot as plt
import mpld3

In [ ]:
A1 = np.random.rand(10,6)
A2 = np.random.rand(6,9)

In [ ]:
u1,s1,v1 = linalg.svd(A1)
A3 = A1.copy()
A3[]

In [ ]:
A1.shape[0]
p = np.random.choice(A1.shape[1])
print(p)

In [ ]:
B1 = A1.copy()
B2 = A2.copy()

# C1 = A1.copy()
# C2 = A2.copy()

In [ ]:
B1[p,:] = [0]*A1.shape[1]
B2[:,p] = [0]*A2.shape[0]



In [ ]:
# A1, B1, A2, B2

In [ ]:
u1, s1, v1 = linalg.svd(np.matmul(A1, A2))
u2, s2, v2 = linalg.svd(np.matmul(B1, B2))

In [ ]:
s1, s2

In [ ]:
l = np.random.choice(10,size=3,replace=False, p=0.1*np.ones(10))
l

In [ ]:

num_trials = 100
svd_check = []
svd_inds = []
dim_in = 50
dim_h = 30
dim_out = 20
diff_p = []
probabilities = list(np.linspace(0,0.9, num=10))
# probabilities = list(np.logspace(-3, -0.01,base=10, num=10))
# probabilities = [0.01, 0.1, 0.2, 0.3, 0.5]
print(probabilities)
for prob in probabilities:

    diff = []
    for i in range(num_trials):
        A1 = np.random.rand(dim_in, dim_h)
        A2 = np.random.rand(dim_h, dim_out)
        drop_out = [1]*dim_h

        while sum(drop_out) >= dim_h: 
            drop_out = np.random.binomial(1, size=dim_h, p=prob)
            drop = [ind  for ind in range(dim_h) if drop_out[ind] ==1]

    #     p = np.random.choice(A1.shape[1])
    #     print(p)
        B1 = A1.copy()
        B2 = A2.copy()
        for p in drop:
            B1[:,p] = [0]*A1.shape[0]
            B2[p,:] = [0]*A2.shape[1]

        u1, s1, v1 = linalg.svd(np.matmul(A1, A2))
        u2, s2, v2 = linalg.svd(np.matmul(B1, B2))
        svd_vals = [1 if a > b else 0 for (a,b) in zip(s1,s2)]
    #     print(svd_vals)
        if prob == 1:
#             print(A1, A2, s1)
            print(B1, B2, s2)
            print(s1[0], s2[0])

        diff.append(s1[0]/s2[0])
        svd_inds.append([ind for ind, e in enumerate(svd_vals) if e == 0])
        svd_check.append(sum(svd_vals))
    diff_p.append(np.mean(diff))
    plt.plot(diff, label = str(prob))
plt.legend()
plt.plot(probabilities, diff_p)

    

In [ ]:
drop_out = np.random.binomial(1, size=dim_h, p=1)
print(drop_out)


In [ ]:
np.logspace(-3, 0,base=10, num=10)

In [ ]:
prob = 0.1
s = []
for i in range(1000):
    s.append(sum(np.random.binomial(1,size=10, p=0.5)))
    

In [ ]:
np.random.binomial(1,size=10, p=0.5)

In [ ]:
#######################################

In [68]:
A1 = np.random.rand(3,4)
A2 = np.random.rand(2,3)
p = np.random.choice(A1.shape[0])
print(p)
x = np.random.rand(4,1)
A1bar = A1.copy()
A2bar = A2.copy()
A1bar[p,:] = [0]*A1.shape[1]
A2bar[:,p] = [0]*A2.shape[0]

1


In [69]:
y = np.matmul(A2, np.matmul(A1,x))
ybar = np.matmul(A2bar, np.matmul(A1bar,x))

In [70]:
# ydiff = np.matmul(A2-A2bar,np.matmul(A1- A1bar, x))
# ydiff = np.matmul(A2[:,p], np.matmul(A1[p,:]))
u=A2[:,p]
v=A1[p,:]
diff = np.matmul(u.reshape(u.shape[0],1),v.reshape(1,v.shape[0]))

In [71]:
diff

array([[0.3949001 , 0.05391626, 0.12681881, 0.26431947],
       [0.08917582, 0.0121753 , 0.02863806, 0.05968827]])

In [55]:
np.matmul(A2,A1).shape

(2, 4)

In [48]:
y == ybar + ydiff

array([[ True],
       [ True]])

In [76]:
A = np.matmul(A2, A1)
Abar = np.matmul(A2bar, A1bar)
A-Abar - diff

array([[ 5.55111512e-17,  4.85722573e-17, -2.77555756e-17,
         0.00000000e+00],
       [ 9.71445147e-17,  3.46944695e-18, -3.46944695e-17,
         7.63278329e-17]])

In [74]:
np.array_equal(A-Abar, diff)

False

In [47]:
np.matmul(A2, A1bar) == np.matmul(A2bar, A1)

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [77]:
A1

array([[0.5460055 , 0.32018965, 0.75527324, 0.42566899],
       [0.92688179, 0.12654847, 0.29766021, 0.6203921 ],
       [0.91615123, 0.59912049, 0.43697664, 0.93880146]])

In [89]:
A = np.zeros((5,5))
A[0:3,0:4] = A1

In [91]:
u1,s1,v1 = np.linalg.svd(A1)
u,s,v = np.linalg.svd(A)

In [92]:
s1, s

(array([2.1092332 , 0.47076338, 0.31777329]),
 array([2.1092332 , 0.47076338, 0.31777329, 0.        , 0.        ]))